### PR TITLE
added <times ago> to the news template

### PR DESCRIPTION
**Pull request by gururani-abhishek**
shows hours if the time between published time and current time is less than 24 otherwise shows difference of days.

### CODE REVIEW

**Comment by gururani-abhishek** [comment]
@AnuragThePathak I got you, also this is my 3rd PR on GitHub. Now after making changes to my code base do I need to close this PR and then make a fresh one again?

**Comment by AnuragThePathak** [comment]
No you simply push the commit to the same and then you'll be able to update PR ig.

**Comment by gururani-abhishek** [comment]
I was figuring out stuff and did something weird, anyway made the changes that you've suggested :)

**Comment by AnuragThePathak** [comment]
Unfortunately I am also having this situation for the first time hence no example. It's just my attempt to write modular code. Anyway I am doing it myself.

**Pull request merged**
